services:
  - type: web
    name: studentportal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn studentdata.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
